channels:
  - conda-forge
dependencies:
  # - cmake  ## Only install on demand.
  - python<3.10
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - pyyaml
    - tqdm
    - fire
    - seaborn
    - numpy
    - torch
    - torchvision
